### ISSUE TITLE
The tables in the platforms sections does not display completely

### ISSUE THREAD

**Issue by Navis-Raven** [platformio/platformio-docs#34] opened 2018-08-24 12:59 UTC
### For example for ESP32:
Like here at the page, at this link: https://docs.platformio.org/en/latest/platforms/espressif32.html#configuration

![image](https://user-images.githubusercontent.com/15887222/44585484-c9673d80-a7ac-11e8-9100-ab683b0cd7b1.png)

### We see the problem particulary here for the STM 32
https://docs.platformio.org/en/latest/platforms/ststm32.html#id114

For example we want to see the continuation of this higlighted line: 
![image](https://user-images.githubusercontent.com/15887222/44585782-ba34bf80-a7ad-11e8-8ff9-52cf61cd1f91.png)

Then we click on scroll to the left, with the mouse at the bottom of the table
![image](https://user-images.githubusercontent.com/15887222/44585829-e0f2f600-a7ad-11e8-961b-70259886221a.png)

And now we try to return to see our line...but where is it ???
![image](https://user-images.githubusercontent.com/15887222/44585924-35967100-a7ae-11e8-8dc8-8eecfbdbda50.png)

**Comment by Navis-Raven** [comment] 2018-10-02 22:59
Is there a functionnality to freeze the first column/line of the tables ? If there is, This will solve the problem

**Comment by ivankravets** [comment] 2018-10-03 22:46
Duplicate of https://github.com/platformio/platformio-docs/issues/5

Tables were refactored. Now, each board has own page with rich documentation.

**Closed by ivankravets** 2018-10-03 22:46 UTC
